In [2]:
import polars as pl

In [6]:
items = pl.read_parquet("../data/items.parquet")
transactions = pl.read_parquet("../data/transactions-2025-12.parquet")

In [8]:
items.shape

(29808, 9)

In [10]:
items.schema

Schema([('item_id', String),
        ('price', Decimal(precision=38, scale=4)),
        ('category_l1', String),
        ('category_l2', String),
        ('category_l3', String),
        ('category', String),
        ('brand', String),
        ('manufacturer', String),
        ('sale_status', Int32)])

In [11]:
items.head(5)

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ category  ┆ brand     ┆ manufactu ┆ sale_sta │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ ---       ┆ ---       ┆ rer       ┆ tus      │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000804000 ┆ 115000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Siêu      ┆ WinWinToy ┆ Không xác ┆ 0        │
│ 0046      ┆ 00        ┆ Sách      ┆           ┆   ┆ nhân,     ┆ s         ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆ robot     ┆           ┆           ┆          │
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Núm ty Dr ┆ Dr.Brown' ┆ Không xác ┆ 0        │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ Brown     ┆ s         ┆ định      ┆          │
│ 000701000 ┆ 176000.00 ┆ Babycare  ┆ Đồ dùng   ┆ … ┆ Dụng cụ   ┆ Pigeon    ┆ Không xác ┆ 0        │
│ 0281      ┆ 00        ┆           ┆ ăn uống   ┆   ┆ ăn uống   ┆           ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆ Pigeon    ┆           ┆           ┆          │
│ 050202034 ┆ 228000.00 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Bình, túi ┆ KUKU      ┆ Không xác ┆ 0        │
│ 0030      ┆ 00        ┆           ┆ phụ kiện  ┆   ┆ ủ sữa     ┆           ┆ định      ┆          │
│ 002002000 ┆ 28000.000 ┆ Thực phẩm ┆ Cháo ăn   ┆ … ┆ Sài Gòn   ┆ Sài Gòn   ┆ CÔNG TY   ┆ 1        │
│ 0253      ┆ 0         ┆ cho bé    ┆ dặm       ┆   ┆ Food      ┆ Food      ┆ CỔ PHẦN   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ SÀI GÒN   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ FOOD -…   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
items.null_count()

shape: (1, 9)
┌─────────┬───────┬─────────────┬─────────────┬───┬──────────┬───────┬──────────────┬─────────────┐
│ item_id ┆ price ┆ category_l1 ┆ category_l2 ┆ … ┆ category ┆ brand ┆ manufacturer ┆ sale_status │
│ ---     ┆ ---   ┆ ---         ┆ ---         ┆   ┆ ---      ┆ ---   ┆ ---          ┆ ---         │
│ u32     ┆ u32   ┆ u32         ┆ u32         ┆   ┆ u32      ┆ u32   ┆ u32          ┆ u32         │
╞═════════╪═══════╪═════════════╪═════════════╪═══╪══════════╪═══════╪══════════════╪═════════════╡
│ 0       ┆ 0     ┆ 0           ┆ 0           ┆ … ┆ 0        ┆ 0     ┆ 0            ┆ 0           │
└─────────┴───────┴─────────────┴─────────────┴───┴──────────┴───────┴──────────────┴─────────────┘

In [13]:
transactions.shape

(3782467, 6)

In [15]:
transactions.schema

Schema([('customer_id', Int32),
        ('item_id', String),
        ('price', Decimal(precision=38, scale=4)),
        ('channel', String),
        ('payment', String),
        ('updated_date', Datetime(time_unit='us', time_zone=None))])

In [18]:
transactions.head(5)

shape: (5, 6)
┌─────────────┬───────────────┬───────────────┬─────────┬────────────────┬─────────────────────────┐
│ customer_id ┆ item_id       ┆ price         ┆ channel ┆ payment        ┆ updated_date            │
│ ---         ┆ ---           ┆ ---           ┆ ---     ┆ ---            ┆ ---                     │
│ i32         ┆ str           ┆ decimal[38,4] ┆ str     ┆ str            ┆ datetime[μs]            │
╞═════════════╪═══════════════╪═══════════════╪═════════╪════════════════╪═════════════════════════╡
│ 7853616     ┆ 2406000000005 ┆ 585000.0000   ┆ iOS     ┆ ShopeePay      ┆ 2025-12-01 12:09:11.467 │
│ 9059471     ┆ 2691000000001 ┆ 83720.0000    ┆ SPE     ┆ Không xác định ┆ 2025-12-16 12:05:55.600 │
│ 8751174     ┆ 0199000000003 ┆ 139000.0000   ┆ SPE     ┆ Tiền mặt       ┆ 2025-12-16 11:24:05.667 │
│ 9090641     ┆ 4950000000002 ┆ 385000.0000   ┆ SPE     ┆ Tiền mặt       ┆ 2025-12-16 12:09:30.447 │
│ 2554844     ┆ 4680000000002 ┆ 45080.0000    ┆ SPE     ┆ Không xác định ┆ 2025-12-16 11:11:18.330 │
└─────────────┴───────────────┴───────────────┴─────────┴────────────────┴─────────────────────────┘

In [17]:
transactions.null_count()

shape: (1, 6)
┌─────────────┬─────────┬───────┬─────────┬─────────┬──────────────┐
│ customer_id ┆ item_id ┆ price ┆ channel ┆ payment ┆ updated_date │
│ ---         ┆ ---     ┆ ---   ┆ ---     ┆ ---     ┆ ---          │
│ u32         ┆ u32     ┆ u32   ┆ u32     ┆ u32     ┆ u32          │
╞═════════════╪═════════╪═══════╪═════════╪═════════╪══════════════╡
│ 0           ┆ 0       ┆ 0     ┆ 0       ┆ 0       ┆ 0            │
└─────────────┴─────────┴───────┴─────────┴─────────┴──────────────┘

In [53]:
# Kiểm tra giá trị duy nhất của cột 'category' trong test
test = items.filter((pl.col('category_l3') == "Núm ty") & (pl.col('sale_status') == 1))
test['category'].unique()

shape: (8,)
Series: 'category' [str]
[
	"Núm ty Aga-ae"
	"Núm ty Tommee Tippee"
	"Núm ty Pigeon"
	"Núm ty Hegen"
	"Núm ty Moyuum"
	"Núm ty Dr Brown"
	"Núm ty Philips Avent"
	"Núm ty Wesser"
]

In [54]:
items['category_l1'].unique()

shape: (15,)
Series: 'category_l1' [str]
[
	"TPCN"
	"Textile"
	"Vệ sinh"
	"Gói Hội Viên"
	"Hóa mỹ phẩm cho bé"
	…
	"Sữa nước"
	"Sữa"
	"Babycare"
	"Thực phẩm cho gia đình"
	"Thực phẩm cho bé"
]